name: example
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  retrofit: ^4.1.0
  json_annotation: ^4.8.0
  dio: ^5.4.0

dev_dependencies:
  swagger_dart_code_generator:
    path: ../
  retrofit_generator: ^8.1.0
  build_runner: ^2.3.3
  json_serializable: ^6.6.1
  lints: ^2.1.1
